"use strict";
const names={2:"Binary",8:"Octal",10:"Decimal",16:"Hexadecimal"};
const system=document.querySelector("#system-select"), digitList=document.querySelector("#digit-list"), weightGrid=document.querySelector("#weight-grid"), systemSummary=document.querySelector("#system-summary");
function digitsFor(base){return Array.from({length:base},(_,i)=>i<10?String(i):String.fromCharCode(55+i)).join(" ");}
function renderSystem(){const b=Number(system.value);digitList.textContent=digitsFor(b);weightGrid.innerHTML=[3,2,1,0].map(p=>`<div class="weight-cell"><span>r<sup>${p}</sup></span><strong>${b**p}</strong></div>`).join("");const v=1*b**3+1*b**2+1*b+1;systemSummary.innerHTML=`In ${names[b].toLowerCase()}, <span class="code-display">1111<sub>${b}</sub></span> equals <strong>${v}<sub>10</sub></strong>.`;}
system.addEventListener("change",renderSystem);renderSystem();
const from=document.querySelector("#from-base"),to=document.querySelector("#to-base"),input=document.querySelector("#number-input"),result=document.querySelector("#conversion-result"),steps=document.querySelector("#conversion-steps");
function clean(s){return s.trim().toUpperCase().replace(/\s+/g,"");}
function validFor(s,b){return s.length>0&&[...s].every(ch=>{const n=parseInt(ch,16);return Number.isInteger(n)&&n<b;});}
function convert(){const f=Number(from.value),t=Number(to.value),raw=clean(input.value);if(!validFor(raw,f)){result.textContent="Invalid digits";steps.innerHTML=`<li>Use only digits valid in base ${f}: ${digitsFor(f)}.</li>`;return;}const dec=parseInt(raw,f),out=dec.toString(t).toUpperCase();result.textContent=`${out} (base ${t})`;let explanation=[];if(f!==10) explanation.push(`Interpret ${raw}<sub>${f}</sub> as a weighted sum to obtain ${dec}<sub>10</sub>.`);else explanation.push(`Start with the decimal value ${dec}.`);if((f===8||f===16)&&(t===2||t===8||t===16)){const width=f===8?3:4;const binary=[...raw].map(ch=>parseInt(ch,16).toString(2).padStart(width,"0")).join("");explanation.push(`Replace each source digit with its ${width}-bit binary equivalent: ${binary}.`);if(t!==2) explanation.push(`Regroup the binary digits in ${t===8?3:4}-bit groups to obtain ${out}<sub>${t}</sub>.`);}else explanation.push(`Repeated division or positional weighting gives ${out}<sub>${t}</sub>.`);steps.innerHTML=explanation.map(x=>`<li>${x}</li>`).join("");}
document.querySelector("#convert-button").addEventListener("click",convert);[from,to,input].forEach(el=>el.addEventListener("change",convert));document.querySelector("#example-button").addEventListener("click",()=>{from.value="8";to.value="16";input.value="674";convert();});convert();
document.querySelector("#quiz-check").addEventListener("click",()=>{const ans=clean(document.querySelector("#quiz-answer").value);const fb=document.querySelector("#quiz-feedback");if(ans==="1BC"){fb.className="feedback correct";fb.textContent="Correct. 674₈ = 110 111 100₂ = 1BC₁₆.";SmartStartProgress.complete("number-systems");}else{fb.className="feedback incorrect";fb.textContent="Not yet. Convert each octal digit to three binary bits, then regroup into four-bit hexadecimal groups.";}});
